# _*_ MakeFile _*_

SOURCES = main.c 
OBJS = ${SOURCES:.c =.o}
CFLAGS = `pkg-config --cflags gtk+-3.0`
LDADD = `pkg-config --libs gtk+-3.0` -lX11 -lavcodec -lavformat -lswscale -lavutil
CC = gcc
PACKAGE = main
all : ${OBJS}
	${CC} ${CFLAGS} -o ${PACKAGE} ${OBJS} ${LDADD}

.c.o:
	${CC} -c $<

clean:
	rm -f *.o

# end of file
